#!/bin/sh
# Copyright 2020-2021 (c) Ed Wildgoose - Nippy Networks UK LLP

# # Flash an LED
#  Supports PCEngines Alix / APU / Skylink
#
# $1 = LED (1-3, etc)
# $2 = Flash State (off|on|heartbeat|flash)
# $3 = delay_on | Flash Speed (fast|medium|slow|occult)
# $4 = delay_off

#
# Show program usage
show_usage() {
	echo "Usage: $0 LED state [speed | delay_on delay_off]"
	echo "Usage: $0 strobe_all (simple|heartbeat1|heartbeat2)"
	echo "	\$1 = LED (1-3, etc)"
	echo "	\$2 = Flash State (off|on|heartbeat|flash)"
	echo "	\$3 = delay_on | Flash Speed (fast|medium|slow|occult)"
	echo "	\$4 = delay_off"

	exit 1
}

#
# Find our LEDs
led_path() {
	led=$1

	local pce_base=$(ls -1d /sys/class/leds/apu*:green:led1 /sys/class/leds/alix:1 2> /dev/null |head -n 1)
	local base
	if [ -n "${pcebase}" ]; then
		base="${pce_base%1}"
		# Return LED path
		echo "${base}${led}"

	elif [ -e "/sys/class/leds/skylink:dg:pwr:blue" ]; then
		base="/sys/class/leds/skylink:dg:pwr:"
		case $led in
			1)
				led=blue
				;;
			2)
				led=green
				;;
			3)
				led=red
				;;
		esac

		echo "${base}${led}"

	else
		echo "Unable to locate LEDs"
		exit 1
	fi
}

# Set some LED param
# $1 = LED
# $2 = Param
# $3 = value
set_param() {
	base_path=$(led_path $1)
	echo $3 > "${base_path}/$2"
}

# Flash
# $1 = LED (1-3)
# $2 = delay_on | Flash Speed (fast|medium|slow|occult)
# $3 = delay_off
set_flash() {
	case $2 in
		fast)
			delay_on=100
			delay_off=100
			;;
		
		medium)
			delay_on=400
			delay_off=400
			;;
		
		slow)
			delay_on=1000
			delay_off=1000
			;;
		
		blink)
			delay_on=100
			delay_off=800
			;;
		
		occult)
			delay_on=800
			delay_off=100
			;;
		
		*)
			delay_on=$2
			delay_off=$3
			;;
	esac
		
	set_param $1 "trigger" "timer"
	set_param $1 "delay_on" "$delay_on"
	set_param $1 "delay_off" "$delay_off"
}



flash_one() {
	case $2 in
		off)
			set_param $1 "trigger" "none"
			set_param $1 "brightness" "0"
			;;

		on)
			set_param $1 "trigger" "none"
			set_param $1 "brightness" "1"
			;;

		heartbeat)
			set_param $1 "trigger" "heartbeat"
			set_param $1 "brightness" "1"
			;;

		flash)
			set_flash $1 $3 $4
			;;

		*)
			# error
			show_usage
			exit 1
			;;
	esac
}

# FIXME: This is a bit of a hack and will only with with sleep times 100-999
strobe_all() {
	case $1 in
		simple)
			d=${2:-180}
			flash_one 1 off; flash_one 2 off; flash_one 3 off
			flash_one 1 flash $d $(($d*2))
			sleep 0.$d
			flash_one 2 flash $d $(($d*2))
			sleep 0.$d
			flash_one 3 flash $d $(($d*2))
			;;

		heartbeat1)
			d=${2:-300}
			flash_one 1 off; flash_one 2 off; flash_one 3 off
			flash_one 1 heartbeat
			sleep 0.$d
			flash_one 2 heartbeat
			sleep 0.$d
			flash_one 3 heartbeat
			;;

		heartbeat2)
			d=${2:-1000}
			flash_one 1 off; flash_one 2 off; flash_one 3 off
			flash_one 1 heartbeat
			sleep 0.$d
			flash_one 2 heartbeat
			sleep 0.$d
			flash_one 3 heartbeat
			;;

		*)
			echo "Unknown strobe_all pattern: $1"
			exit 1
			;;
	esac
}

# Check params
if [ "$#" -lt "2" ] || [ "$2" = "flash" -a "$#" -lt "3" ]; then
	show_usage
	exit 1
fi

# Main code
case $1 in
	strobe_all)
		strobe_all $2 $3
		;;

	*)
		flash_one $*
		;;
esac
